# Spam Email Detection
Spam email is unwanted, unsolicited, and often fraudulent messages that are sent in bulk to a large audience. Spam emails can clog up your inbox, waste your time, and even contain viruses or malicious links. With machine learning, it's possible to train a computer to automatically identify and block spam emails.

In [2]:
# Import libraries
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

In [3]:
# Load the spam email dataset
data = fetch_20newsgroups(subset='all', categories=['alt.atheism', 'comp.graphics', 'sci.space'])

In [7]:
# Create the feature matrix and target vector
x = data.data
y = data.target

In [8]:
# Split the dataset to taining and testting sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [12]:
# Convert the text data into numerical features using CountVectorizer
cv = CountVectorizer()
x_train_cv = cv.fit_transform(x_train)
x_test_cv = cv.transform(x_test)

In [14]:
# Train the naive bayes classifire
model = MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [15]:
# Predict the model with test data
y_pred = model.predict(x_test_cv)

In [17]:
# calculate the accuracy score and confusion matrix
acc_score = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

In [18]:
print('Accuracy Score:', acc_score)
print('Confusion Matrix:\n', cm)

Accuracy Score: 0.9758454106280193
Confusion Matrix:
 [[259   1   2]
 [  1 270   5]
 [  1  10 279]]
