# Data Preprocessing

## Import the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Import the Dataset

In [7]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [12]:
x_df = pd.DataFrame(X)
y_df = pd.DataFrame(y)

In [13]:
x_df

0     1        2
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [14]:
y_df

0
0   No
1  Yes
2   No
3   No
4  Yes
5  Yes
6   No
7  Yes
8   No
9  Yes

## Taking care of missing data

In [15]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [16]:
x_df = pd.DataFrame(X)
x_df

0          1             2
0   France       44.0       72000.0
1    Spain       27.0       48000.0
2  Germany       30.0       54000.0
3    Spain       38.0       61000.0
4  Germany       40.0  63777.777778
5   France       35.0       58000.0
6    Spain  38.777778       52000.0
7   France       48.0       79000.0
8  Germany       50.0       83000.0
9   France       37.0       67000.0

## Encoding categorical data

### Encoding the Independent Variable

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [21]:
x_df = pd.DataFrame(X)
x_df

0    1    2          3             4
0  1.0  0.0  0.0       44.0       72000.0
1  0.0  0.0  1.0       27.0       48000.0
2  0.0  1.0  0.0       30.0       54000.0
3  0.0  0.0  1.0       38.0       61000.0
4  0.0  1.0  0.0       40.0  63777.777778
5  1.0  0.0  0.0       35.0       58000.0
6  0.0  0.0  1.0  38.777778       52000.0
7  1.0  0.0  0.0       48.0       79000.0
8  0.0  1.0  0.0       50.0       83000.0
9  1.0  0.0  0.0       37.0       67000.0

### Encoding the Dependent Variable

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [24]:
y_df = pd.DataFrame(y)
y_df

0
0  0
1  1
2  0
3  0
4  1
5  1
6  0
7  1
8  0
9  1

## Spliting the dataset into tain and test

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [27]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [28]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [29]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [30]:
print(y_test)

[0 1]


## Feature Scaling

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [36]:
print(X_train)

[[0.0 0.0 1.0 -0.1915918438457856 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057902 -0.07013167641635401]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.3045301939022488 -0.30786617274297895]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]


In [37]:
print(X_test)

[[0.0 1.0 0.0 -1.0000000000000002 -1.0000000000000002]
 [1.0 0.0 0.0 0.9999999999999999 0.9999999999999997]]
